Auto push to pypi
ncskth/durin pull request #6
Opened 2022-10-01 14:10 UTC by JohannesLusk

This workflow will automatically push to pypi if a commit has a tag. The auto tag generation and pushing doesn't work as of yet.

2022-10-03 17:06 UTC, Jegp requested changes
Nice work! I enjoy reading the commit log :P

Does this work with the tagging? If so, I guess we should push to the "real" pypi and not the test one? 
Also, should `ChangeVersionNumber.py` be in `.gitignore`?

2022-10-04 11:53 UTC, Jegp requested changes
Nice. LGTM! The only oddity I see is the addition of your change version number Python script into .gitignore. But once you change from `test.pypi.org` to the official repo, I'm happy to merge!

2022-10-04 11:53 UTC, Jegp commented on .gitignore
> +ChangeVersionNumber.py
Shouldn't this line be kept out? I assume you'll want to **keep** the `ChangeVersionNumber.py` file, no?

2022-10-04 12:18 UTC, JohannesLusk commented on .gitignore
> +ChangeVersionNumber.py
Alrighty, Will do so, I tried to figure out the no start on push issue, gave up, and restructured it into two jobs instead. This should have the same effect with a lot less headache for me. See last commit

2022-10-08 20:32 UTC, Jegp requested changes
Ok, I think this is definitely progress, but it's not good if you run end up recursing too much. We really have to understand that before we can merge this. One possible approach could be to use this piece of code: https://github.com/marketplace/actions/github-tag

However, I _really_ think we should start with *just* the releasing. Meaning, just focusing on the push to PyPi when a new release is **manually** made. After that I'm happy to focus on making neat version number changes. But we can always automate that later.

2022-10-10 08:20 UTC, Jegp approved these changes
LGTM! :partying_face:

2022-10-10 08:23 UTC, merged